spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql:///Spring
    dbcp2:
      min-idle: '5'
      max-total: '20'
    type: org.apache.commons.dbcp2.BasicDataSource
    password: raghava@17
  application:
    name: BootProj03_RealTimeDI
